spring:
  mvc:
    hiddenmethod:
      filter:
        enabled: true
        
  servlet:
   multipart:
     max-file-size: 20MB
     max-request-size: 20MB
     
  datasource:
   #driver-class-name: org.h2.Driver
   #url: jdbc:h2:mem:pictgram
   #username: sa
   #password: 
   driver-class-name: org.postgresql.Driver
   url: jdbc:postgresql://localhost:5432/pictgram
   username: ${psql.user}
   password: ${psql.password}

  h2:
    console:
      enabled: true  
  mail:
    default-encoding: UTF-8
    protocol: smtp
    host: ${spring.mail.host}
    port: ${spring.mail.port}
    username: ${spring.mail.username}
    password: ${spring.mail.password}
    properties: 
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
  thymeleaf:
    check-template-location: false    
debug: true
    
image:
  local: true

logging:
    level:
      root: info 
    file:
      name: test
      
onesignal:
  id: ${onesignal.id}
  
googlemap:
  key: ${googlemap.key}